version: "3.3"

services:

  backend:
    image: ${BACKEND_REGISTRY_IMAGE}/sausage-backend:latest
    restart: always
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      SPRING_FLYWAY_ENABLED: "false"
      REPORT_PATH: "./logs"
      VIRTUAL_HOST: backend
    networks:
      - sausage_network

  reports:
    image: ${BACKEND_REPORT_REGISTRY_IMAGE}/sausage-backend-report:latest
    container_name: reports
    restart: always
    environment:
      DB: ${DB}
    networks:
      - sausage_network

  frontend:
    image: ${FRONTEND_REGISTRY_IMAGE}/sausage-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=backend
    networks:
      - sausage_network

networks:
  sausage_network:
