version: "3.3"

services:

  backend_blue:
    image: ${BACKEND_REGISTRY_IMAGE}/sausage-backend:latest
    env_file:
      - backend.env
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: backend
    healthcheck:
      test: curl http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 6
    networks:
      - sausage_network
  
  backend_green:
    image: ${BACKEND_REGISTRY_IMAGE}/sausage-backend:latest
    env_file:
      - backend.env
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: backend
    healthcheck:
      test: curl http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 6
    networks:
      - sausage_network

  reports:
    image: ${BACKEND_REPORT_REGISTRY_IMAGE}/sausage-backend-report:latest
    env_file:
      - reports.env
    container_name: reports
    restart: always
    environment:
      DB: ${DB}
    networks:
      - sausage_network

  frontend:
    image: ${FRONTEND_REGISTRY_IMAGE}/sausage-frontend:latest
    env_file:
      - frontend.env
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=backend
    networks:
      - sausage_network

networks:
  sausage_network:
