DROP TABLE IF EXISTS order_product;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS product;

CREATE TABLE order_product
(
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL

);

CREATE TABLE orders
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    date_created date,
    status varchar(255)
);

CREATE TABLE product
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    picture_url varchar(255),
    price double precision
);
