stages:
  - build
  - notify
  - test

include:
  - template: Security/SAST.gitlab-ci.yml   # для проверки кода тестами от Gitlab CI

build-backend-code-job:  # сборка бэкэнда
  stage: build  
  only:
    changes:
    - backend/*          # только если есть изменения в каталоге бэкэнда
  script:
    - cd backend
    - mvn package -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository    # сборка проекта
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar  # сохраняем артефакт для Deployment'а
      - $CI_PROJECT_DIR/.m2/                           # сохранение зависимостей для SAST 

telegram-notification-backend:
  stage: notify
  script:
    - 'curl -X POST -H "Content-Type: application/json"
      -d "{\"chat_id\": \"-1001823350512\", \"parse_mode\":\"markdown\",
      \"text\": \"\uD83D\uDE80 *Данил Кузнецов* собрал BACKEND.\n
      \uD83D\uDD3D [Download backend artifact](https://gitlab.praktikum-services.ru/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/release-0.0.1/download?job=build-backend-code-job&job_token=$CI_JOB_TOKEN&private_token=$PROJECT_ACCESS_TOKEN)\n
      Branch: $CI_COMMIT_REF_SLUG\"}"
      https://api.telegram.org/$TELEGRAM_BOT_TOKEN/sendMessage'
  needs:
    - build-backend-code-job    # если успешно собрали бэк
  rules:
    - if: $CI_COMMIT_TITLE =~ /send notification/   # если заголовок коммита содержит фразу "send notification"

spotbugs-sast:                # SAST тест от GitLab CI
  dependencies:
    - build-backend-code-job
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 17
    MAVEN_REPO_PATH: $CI_PROJECT_DIR/.m2/repository

sonarqube-backend-sast:       # SAST тест от SonarQube
  stage: test
  image: maven:3.8-openjdk-16 # docker-образ
  script:
    - cd backend
    - >
      mvn verify sonar:sonar
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectName=${SONAR_PROJECT_NAME_BACK}
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACK}
      -Dsonar.host.url=${SONAR_URL}
      -Dsonar.login=${SAUSAGE_STORE_14_BACK_TOKEN}
  needs:
    - build-backend-code-job    # если успешно собрали бэк